// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrV8xp0-BQLeOnNScf0V7KBp-lE3V4xiA',
    appId: '1:1098149817464:web:37082fe06453a8946d118d',
    messagingSenderId: '1098149817464',
    projectId: 'doclink-8a2f7',
    authDomain: 'doclink-8a2f7.firebaseapp.com',
    storageBucket: 'doclink-8a2f7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjIUG0hplUnp8anFqdU68KA_P1t8QIv7M',
    appId: '1:1098149817464:android:8671a530104c65c66d118d',
    messagingSenderId: '1098149817464',
    projectId: 'doclink-8a2f7',
    storageBucket: 'doclink-8a2f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNG4TztRXeb6ed6dN5qC3UVnv_lOlanTk',
    appId: '1:1098149817464:ios:d78e6b96559a26426d118d',
    messagingSenderId: '1098149817464',
    projectId: 'doclink-8a2f7',
    storageBucket: 'doclink-8a2f7.firebasestorage.app',
    iosBundleId: 'com.example.docLinkProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNG4TztRXeb6ed6dN5qC3UVnv_lOlanTk',
    appId: '1:1098149817464:ios:d78e6b96559a26426d118d',
    messagingSenderId: '1098149817464',
    projectId: 'doclink-8a2f7',
    storageBucket: 'doclink-8a2f7.firebasestorage.app',
    iosBundleId: 'com.example.docLinkProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrV8xp0-BQLeOnNScf0V7KBp-lE3V4xiA',
    appId: '1:1098149817464:web:f96a282f6cdacdf86d118d',
    messagingSenderId: '1098149817464',
    projectId: 'doclink-8a2f7',
    authDomain: 'doclink-8a2f7.firebaseapp.com',
    storageBucket: 'doclink-8a2f7.firebasestorage.app',
  );

}